#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	forward(30, seconds, 50);
	wait(2, seconds);
	backward(3, seconds, 50);
}
