#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Tree.h"
int node_id;
int current_node;
int back;
//fungsi=======================================================

void Add_Anak(int Id, int L, int M, int R)
/*Menambahkan anak kiri, kanan, dan tengah ke sebuah node Id,
*/
{
	setLeft(&mem[Id], L);
	setMid(&mem[Id], M);
	setRight(&mem[Id], R);
}

int Aloc(int Id, int Pa)
/* Menghasilkan sebuah node Id, dengan parent Pa. Node tidak punya anak.
	Mengembalikan id node.
*/
{
	setId(&mem[Id], Id);
	setParent(&mem[Id], Pa);
	return Id;
}

//bergerak memutar balik robot
void putarBalik()
{
	back = 1;
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 70);
	sleep(1000);
}

//gerak mengikuti garis hitam
void maju()
{
	float temp = (float) getColorReflected(colorSensor) * 2+ 20;
	motor[leftMotor]  = temp;
	motor[rightMotor] = 220 - temp;
}

//cariJalan******************************************************************

void gerak()
{
	repeat(forever)
	{
		if(getColorName(colorSensor)==colorBlue)
		{
			break;
		}
		else if(getColorName(colorSensor)==colorGreen)
		{
			if (back == 0){
				Next_Node_Parent();
			}
			else {
				Next_Node();
				back = 0;
			}
		}
		else if(getColorName(colorSensor)==colorRed)
		{
			putarBalik();
		}
		else //warna item
		{
			maju();
		}
	}
}

//cek apakah ada jalan lurus
bool cekLurus()
{
	bool is_node = false;
	setMotorSpeed(leftMotor, 60);
	setMotorSpeed(rightMotor, 60);
	sleep(600);
	if(getColorName(colorSensor)==colorBlack)
	{
		is_node = true;
	}
	return is_node;
}

//cek apakah ada jalan kanan
bool cekKanan()
{
	bool is_node = false;
	setMotorSpeed(leftMotor, 60);
	setMotorSpeed(rightMotor, 23);
	sleep(1000);
	if(getColorName(colorSensor)==colorBlack)
	{
		is_node = true;
	}
	return is_node;
}

//cek apakah ada jalan kiri
bool cekKiri()
{
	bool is_node = false;
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 50);
	sleep(1000);
	if(getColorName(colorSensor)==colorBlack)
	{
		is_node = true;
	}
	return is_node;
}

//Robot sudah menyusuri sebuah jalur namun belum bertemu solusi
// lalu balik lagi ke persimpangan sebelumnya. Prosedur void memberitahu robot
// Node mana lagi yang perlu dijalankan. Jika anak kanan sudah, maka selanjutnya lurus,
//Jika lurus sudah maka selanjutnya anak kiri.
void Next_Node() {
	current_node = mem[current_node].Parent;
	int Kanan = -1, Kiri = -1, Lurus = -1;
	if (cekKanan()) {
		Lurus = Aloc(node_id, current_node);
		Add_Anak(current_node, Kiri, Lurus, Kanan);
		current_node = mem[current_node].Mid;
		node_id++;
		}
		else {
			setMotorSpeed(leftMotor, -60);
			setMotorSpeed(rightMotor, -23);
			sleep(1000);

			if (cekLurus()) {
			Kiri = Aloc(node_id, current_node);
			Add_Anak(current_node, Kiri, Lurus, Kanan);
			current_node = mem[current_node].Left;
			node_id++;
			}
		}
}

void Next_Node_Parent() {
	int Kanan = -1, Kiri = -1, Lurus = -1;
	if (cekKanan()) {
		Kanan = Aloc(node_id, current_node);
		Add_Anak(current_node, Kiri, Lurus, Kanan);
		current_node = mem[current_node].Right;
		node_id++;
	}
	else {
		setMotorSpeed(leftMotor, -60);
		setMotorSpeed(rightMotor, -30);
		sleep(1000);

		if (cekLurus()) {
		Lurus = Aloc(node_id, current_node);
		Add_Anak(current_node, Kiri, Lurus, Kanan);
		current_node = mem[current_node].Mid;
		node_id++;
		}
		else {
			setMotorSpeed(leftMotor, -60);
			setMotorSpeed(rightMotor, -60);
			sleep(1000);

			if (cekKiri()) {
			Kiri = Aloc(node_id, current_node);
			Add_Anak(current_node, Kiri, Lurus, Kanan);
			current_node = mem[current_node].Left;
			node_id++;
			}
			else {
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, -55);
				sleep(1000);
			}
		}
	}
	//tidak punya node kanan, langsung lurus
}

task main()
{
	node_id = 0;
	current_node = 0;
	back = 0;
	//maju dikit biar kaga kena biru
	int i;
	for (i = 0; i < 100; i++) {
		mem[i].Id = -1;
		mem[i].Left = -1;
		mem[i].Mid = -1;
		mem[i].Right = -1;
		mem[i].Parent = -1;
	}
	setMotorSpeed(leftMotor, 100);
	setMotorSpeed(rightMotor, 100);
	sleep(1000);
	setMotorSpeed(rightMotor, 50);
	setMotorSpeed(leftMotor, 0);
	sleep(300);

	current_node = Aloc(node_id, Nil);
	node_id++;
	//mulai algoritma gerak warna
	gerak();
}
