#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Tree.h"
int node_id;
int current_node;
int back;
int batas_kedalaman;
int kedalaman;
int origin_node;
//fungsi=======================================================

void Add_Anak(int Id, int L, int M, int R)
/*Menambahkan anak kiri, kanan, dan tengah ke sebuah node Id,
*/
{
	setLeft(&mem[Id], L);
	setMid(&mem[Id], M);
	setRight(&mem[Id], R);
}

int Aloc(int Id, int Pa)
/* Menghasilkan sebuah node Id, dengan parent Pa. Node tidak punya anak.
	Mengembalikan id node.
*/
{
	setId(&mem[Id], Id);
	setParent(&mem[Id], Pa);
	return Id;
}

//bergerak memutar balik robot
void putarBalik()
{
	back = 1;
	setMotorSpeed(rightMotor, 0);
	setMotorSpeed(leftMotor, 50);
	sleep(1500);
}

//gerak mengikuti garis hitam
void maju()
{
	float temp = (float) getColorReflected(colorSensor) *3/5  + 20;

	if(getColorReflected(colorSensor) >= 95)
	{
		motor[rightMotor]  = 40;
		motor[leftMotor] = 0;
		sleep(500);
	}
	else
	{
		motor[leftMotor]  =  40 + temp;
		motor[rightMotor] =  40 + 60 - temp;
	}
}

//cariJalan******************************************************************

void gerak()
{
	repeat(forever)
	{
		if(getColorName(colorSensor)==colorBlue)
		{
			break;
		}
		else if(getColorName(colorSensor)==colorGreen)
		{
			if (back == 0){
				kedalaman += 1;
				if (kedalaman < batas_kedalaman ) {
					Next_Node_Parent();
				}
				else {
					putarBalik();
					kedalaman -=1;
				}
			}
			else {
				Next_Node();
				back = 0;
			}
		}
		else if(getColorName(colorSensor)==colorRed)
		{
			putarBalik();
		}
		else //warna item
		{
			maju();
		}
	}
}

//cek apakah ada jalan lurus
bool cekLurus()
{
	bool is_node = false;
	setMotorSpeed(leftMotor, 60);
	setMotorSpeed(rightMotor, 60);
	sleep(650);
	if(getColorName(colorSensor)==colorBlack)
	{
		is_node = true;
	}
	return is_node;
}

//cek apakah ada jalan kanan
bool cekKanan()
{
	bool is_node = false;
	setMotorSpeed(leftMotor, 60);
	setMotorSpeed(rightMotor, 27);
	sleep(1000);
	if(getColorName(colorSensor)==colorBlack)
	{
		is_node = true;
	}
	return is_node;
}

//cek apakah ada jalan kiri
bool cekKiri()
{
	bool is_node = false;
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 50);
	sleep(1000);
	if(getColorName(colorSensor)==colorBlack)
	{
		is_node = true;
	}
	return is_node;
}

void free_mem() {
	int i;
		for (i = 0; i < 100; i++) {
		mem[i].Id = -1;
		mem[i].Left = -1;
		mem[i].Mid = -1;
		mem[i].Right = -1;
		mem[i].Parent = -1;
	}
}

//Robot sudah menyusuri sebuah jalur namun belum bertemu solusi
// lalu balik lagi ke persimpangan sebelumnya. Prosedur void memberitahu robot
// Node mana lagi yang perlu dijalankan. Jika anak kanan sudah, maka selanjutnya lurus,
//Jika lurus sudah maka selanjutnya anak kiri.
void Next_Node() {
	int prev_node = current_node;
	current_node = mem[current_node].Parent;
	int Kanan = -1, Kiri = -1, Lurus = -1;
	if (prev_node == mem[current_node].Right) {
		if (cekKanan()) {
			Lurus = Aloc(node_id, current_node);
			Add_Anak(current_node, Kiri, Lurus, Kanan);
			current_node = mem[current_node].Mid;
			node_id++;
			}
			else {
				setMotorSpeed(leftMotor, -60);
				setMotorSpeed(rightMotor, -27);
				sleep(1000);

				if (cekLurus()) {
				Kiri = Aloc(node_id, current_node);
				Add_Anak(current_node, Kiri, Lurus, Kanan);
				current_node = mem[current_node].Left;
				node_id++;
				}
				else {
					if (current_node == origin_node) {
						batas_kedalaman += 1;
						free_mem();
						setMotorSpeed(leftMotor, 50);
						setMotorSpeed(rightMotor, 0);
						sleep(700);
						setMotorSpeed(leftMotor, -50);
						setMotorSpeed(rightMotor, -50);
						sleep(300);
					}
					else if (cekKiri()){
						back = 1;
					}
				}
			}
	}
	else if (prev_node == mem[current_node].Mid) {
		if (cekKanan()) {
			Kiri = Aloc(node_id, current_node);
			Add_Anak(current_node, Kiri, Lurus, Kanan);
			current_node = mem[current_node].Mid;
			node_id++;
			}
			else {
				setMotorSpeed(leftMotor, -60);
				setMotorSpeed(rightMotor, -25);
				sleep(1000);

				if (current_node == origin_node) {
					batas_kedalaman += 1;
					free_mem();
					setMotorSpeed(leftMotor, 50);
					setMotorSpeed(rightMotor,50);
					sleep(1200);
					setMotorSpeed(leftMotor, 50);
					setMotorSpeed(rightMotor, 10);
					sleep(900);
				}
				else if (cekKanan()){
					back = 1;
				}
			}
	}
	else {
		if (current_node == origin_node) {
			batas_kedalaman += 1;
			free_mem();
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, 50);
				sleep(700);
				setMotorSpeed(leftMotor, -50);
				setMotorSpeed(rightMotor, -50);
				sleep(300);

		}
		else if (cekKanan()){
			back = 1;
		}
	}
}

void Next_Node_Parent() {
	int Kanan = -1, Kiri = -1, Lurus = -1;
	if (cekKanan()) {
		Kanan = Aloc(node_id, current_node);
		Add_Anak(current_node, Kiri, Lurus, Kanan);
		current_node = mem[current_node].Right;
		node_id++;
	}
	else {
		setMotorSpeed(leftMotor, -60);
		setMotorSpeed(rightMotor, -30);
		sleep(1000);

		if (cekLurus()) {
		Lurus = Aloc(node_id, current_node);
		Add_Anak(current_node, Kiri, Lurus, Kanan);
		current_node = mem[current_node].Mid;
		node_id++;
		}
		else {
			setMotorSpeed(leftMotor, -60);
			setMotorSpeed(rightMotor, -60);
			sleep(1000);

			if (cekKiri()) {
			Kiri = Aloc(node_id, current_node);
			Add_Anak(current_node, Kiri, Lurus, Kanan);
			current_node = mem[current_node].Left;
			node_id++;
			}
			else {
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, -55);
				sleep(1000);
			}
		}
	}
	//tidak punya node kanan, langsung lurus
}

task main()
{
	node_id = 0;
	current_node = 0;
	back = 0;
	batas_kedalaman = 2;
	kedalaman  = 0;
	int i;
	for (i = 0; i < 100; i++) {
		mem[i].Id = -1;
		mem[i].Left = -1;
		mem[i].Mid = -1;
		mem[i].Right = -1;
		mem[i].Parent = -1;
	}

	//maju dikit biar kaga kena bir
	//setMotorSpeed(leftMotor, 50);
	//setMotorSpeed(rightMotor, 50);
	//sleep(3000);
	//belok dikit
	//setMotorSpeed(rightMotor, 50);
	//setMotorSpeed(leftMotor, 0);
	//sleep(300);

	current_node = Aloc(node_id, Nil);
	origin_node = 0;
	node_id++;
	//mulai algoritma gerak warna
	gerak();
}
